#+BEGIN_OPTIONS
#+AUTHOR: William F. Schneider
#+TITLE: CBE 60553 Syllabus
#+EMAIL: wschneider@nd.edu
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{epstopdf}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage[labelfont=bf]{caption}
#+LATEX_HEADER:\usepackage{setspace}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0.5pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0.5pt}
#+LATEX_HEADER:\lfoot{\today}
#+LATEX_HEADER:\cfoot{\copyright\ 2017 W.\ F.\ Schneider}
#+LATEX_HEADER:\rfoot{\thepage}
#+LATEX_HEADER:\title{University of Notre Dame\\Advanced Chemical Engineering Thermodynamics\\(CBE 60553)}
#+LATEX_HEADER:\author{Prof. William F.\ Schneider}
#+LATEX_HEADER:\usepackage{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsection}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\titlespacing*{\subsubsection}
#+LATEX_HEADER:{0pt}{0.4\baselineskip}{0.1\baselineskip}

#+EXPORT_EXCLUDE_TAGS: noexport
#+OPTIONS: toc:nil
#+OPTIONS: H:3 num:3
#+OPTIONS: ':t
#+END_OPTIONS

#+BEGIN_EXPORT latex
\begin{center}
\textsc{\Large Advanced Chemical Engineering Thermodynamics (CBE 60553)}\\University of Notre Dame, Fall 2017
\end{center}
\begin{tabular*}{\textwidth}{@{\extracolsep{\fill}}l r}
\hline
Prof.\ Bill Schneider & Classroom: 115 O'Shag\\
Office: 123b Cushing & Lecture MWF 10:30-11:20\\
\email{wschneider@nd.edu}, phone 574-631-8754 & \\
\hline
\end{tabular*}
#+END_EXPORT

* Thermodynamics
Thermodynamics is the most complete and elegant of all the physical theories we have to describe the world around us. To paraphrase Einstein, it is the only theory that we are certain will never change. It is beautiful in its simplicity yet surprisingly challenging to apply in practice. It is central to all elements of Chemical Engineering, and for that reason most essential for you have a firm foundation in.

In this class we will take a fundamental approach to thermodynamics. Our goal is for you to understand the underlying concepts well, so that you can apply them to your own problems of interest. We begin with a refresher on the basic mathematical structure of thermodynamics. We’ll then delve into the immutable microscopic underpinnings of thermodynamics. That microscopic picture is the bridge to understanding the thermodynamic properties of gases, liquids, and mixtures. Lastly, we will explore the thermodynamics of reactions, phase change, and non-equilibrium behavior.

I strongly encourage you to keep up with the reading and homework and to bring up questions in class. Don’t be bashful: if you don’t understand something, chances are that many of your classmates (and quite possibly your instructor!) don’t either.

* Texts
** Primary
- De Pablo and Schieber, /Molecular Engineering Thermodynamics/, Cambridge 2014

** Supporting
- McQuarrie and Simon, /Molecular Thermodynamics/, University Science Books, 1999;
- H. B. Callen, /Thermodynamics and an Introduction to Thermostatistics/ 2nd ed., Wiley 1985;
- Tester and Modell, /Thermodynamics and its Applications/, Prentice-Hall, 1997

* Web
This syllabus, reading assignment, the homework assignments and solutions, a summary of the lecture schedule, and a *detailed course outline* are available on the web at [[https://github.com/wmfschneider/CBE60553]].

* Format
The topics will be presented in a series of self-contained lectures as
outlined on the website. Lecture notes for each lecture will be posted
on-line. Attendance is expected, and you should be prepared to ask
and answer questions.

* Topics
See [[https://github.com/wmfschneider/CBE60553/blob/master/lectures.org][https://github.com/wmfschneider/CBE60553/lectures.org]].

* Homework
Nine problem sets will be distributed during the semester and will be due at the beginning of class on dates to be announced. The problem sets will be designed to reinforce your knowledge and ability to apply the course material.  *Assignments turned in late will automatically lose 20%, and those turned in after the solutions are posted will not be accepted.*  Your lowest score on homework will be dropped.  You may discuss the homework with your classmates, but *what you turn in must be your own work.*

Homework will in general require some computations. You may write out solutions by hand. Alternatively, homework will also be distributed as [[https://ipython.org/notebook.html][iPython notebooks]], a format that allows you to solve problems using Python within the notebook.
* Homework Defense
To help me get to know you and how you are doing with the course, after each homework assignment two of you will be chosen at random to meet with me one-on-one to defend your homework answers.

* Grading
Grades will be based on the homework (30%), two in-class exams (40%), and a cumulative final (30%).

* Academic honesty
Should go without saying. Any cheating or misrepresenting of work as your own will be dealt with according to the Honor Code policies of the University. I reserve the right to relocate any students during an examination at my discretion.

* Professional courtesy
As a courtesy to the instructor and your classmates, please refrain from
texting, web browsing, tweeting, updating, or using your phone or laptop for any
purpose during class time.  If you must use an electronic device, excuse
yourself from class.

* Office hours
The instructor will be available Wednesdays 3:30-4:30 or by appointment to discuss the course and homework.

