#+BEGIN_OPTIONS
#+AUTHOR: William F. Schneider
#+TITLE: CBE 60553 Homework
#+EMAIL: wschneider@nd.edu
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{epstopdf}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\usepackage[labelfont=bf]{caption}
#+LATEX_HEADER:\usepackage{setspace}
#+LATEX_HEADER:\setlength{\headheight}{10.2pt}
#+LATEX_HEADER:\setlength{\headsep}{20pt}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0.5pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0.5pt}
#+LATEX_HEADER:\lfoot{\today}
#+LATEX_HEADER:\cfoot{\copyright\ 2016 W.\ F.\ Schneider}
#+LATEX_HEADER:\rfoot{\thepage}
#+LATEX_HEADER:\chead{\bf{Advanced Chemical Engineering Thermodynamics (CBE 60553)\vspace{12pt}}}
#+LATEX_HEADER:\lhead{\bf{Homework 2}}
#+LATEX_HEADER:\rhead{\bf{Due September 19, 2016}}
#+LATEX_HEADER:\usepackage{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\title{University of Notre Dame\\Advanced Chemical Engineering Thermodynamics\\(CBE 60553)}
#+LATEX_HEADER:\author{Prof. William F.\ Schneider}
#+LATEX_HEADER:\usepackage{siunitx}
#+LATEX_HEADER:\usepackage[version=3]{mhchem}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}

#+OPTIONS: toc:nil
#+OPTIONS: H:3 num:3
#+OPTIONS: ':t
#+END_OPTIONS

\noindent *Solve each problem on separate sheets of paper, and clearly indicate the problem number and your name on each.  Carefully and neatly document your answers.  You may use a mathematical solver like Python. Use plotting software for all plots.*

* Maximum work, minimum work
One mole of a monatomic ideal gas is contained in a cylinder of volume
  $10^{-3}~\text{m}^3$ at \SI{400}{K}.  The gas is to be brought to a final state of
  twice the volume and the same temperature.

1. What is the maximum work that can be delivered to a reversible work
  source, assuming a \SI{300}{K} thermal reservoir is available?

2. One way to extract this work would be to expand the gas adiabatically to
  300 K, compress it isothermally at 300 K, and finally compress it
  adiabatically to the final state.  Find the work and heat transfers in each step.

3. What is the minimum work necessary to return the gas to its initial
  state, assuming the same 300 K reservoir is available?

* Work of separation
A geothermal source is to be used to power a plant that separates oxygen from
  air. The geothermal source comprises a well containing $10^3~\text{m}^3$ of
  water initially at $100^\circ\text{C}$; nearby there is a very big ($>>
  10^3~\text{m}^3$ ) lake at $5^\circ\text{C}$.

1. What is the theoretical maximum amount of work that could be extracted from the power source?
  Assume the heat capacity of \ce{H2O} is $4.2~\text{J}~\text{(g K)}^{-1}$, independent of temperature.

\noindent Suppose you'd like to use the work from the geothermal source to
  extract oxygen from air.  The atmosphere is a comfy $20^\circ\text{C}$ and can
  be treated as an ideal gas mixture of 80\% \ce{N2} and 20\% \ce{O2} at 1 atm.
  The fundamental equation of an ideal gas mixture is like that of an ideal gas,
  with the addition of terms related to the mixture composition. It's convenient
  to write the composition in terms of mole fraction, $x_{j} = N_{j}/N$, where
  $N = \sum_{j}N_{j}$.  The fundamental equation can be written

\begin{equation}
S(T,P,N_{1},N_{2},\ldots) = c R \ln\left ( \frac{T}{T_{0}} \right ) - R \ln\left ( \frac{P}{P_{0}} \right ) - R \sum_{j}x_{j}\ln x_{j} + \sum_{j}x_{j}s_{0,j}
\end{equation}

\noindent where $P = NRT/V$ and $U=cNRT$.

2. What is the maximum number of moles of \ce{O2} that could be produced from the geothermal source?  Assume the separation is carried out at constant temperature and pressure.

3. Propose some plausible way that the separation could be carried out.

* Keeping it cold
A household refrigerator is kept at  $2^\circ\text{C}$.  Every time the door is open
   to put something inside, 200 kJ of heat are added to the refrigerator and the
   temperature inside changes negligibly.  The door is opened 15 times a day, and the
   refrigerator operates at 15\% of theoretical maximum efficiency.  The cost of
   electricity is \$0.10/kW h.

1. Derive an expression for the theoretical maximum efficiency?

2. How much does it cost to run the refrigerator for a month?


* Work with an ideal gas :no_export:
When an ideal monatomic gas is placed inside a piston and compressed
  quasi-statically, the temperature and volume are observed to vary according
  to
  \begin{equation*}
    T=\left ( \frac{V}{V_0}\right )^\eta T_0
  \end{equation*}
where $\eta$ is a constant.

1. Calculate the work $w$ done on the gas when one mole is compressed from $V_0$ to
    $V_1 < V_0$.

2. Calculate the corresponding change in energy $\Delta U$ of the gas.

3. Calculate the corresponding heat transfered to the gas $q$ by energy balance.

4. Calculate the heat transfered to the gas $q$ by integrating $\dbar q = T dS$.

5. Calculate the value of $\eta$ for which $q = 0$.
