#+BEGIN_OPTIONS
#+AUTHOR: William F. Schneider
#+TITLE: CBE 60553 Homework
#+EMAIL: wschneider@nd.edu
#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER:\usepackage[left=1in, right=1in, top=1in, bottom=1in, nohead]{geometry}
#+LATEX_HEADER:\geometry{margin=1.0in}
#+LATEX_HEADER:\usepackage{hyperref}
#+LATEX_HEADER:\usepackage{amsmath}
#+LATEX_HEADER:\usepackage{graphicx}
#+LATEX_HEADER:\usepackage{epstopdf}
#+LATEX_HEADER:\usepackage{fancyhdr}
#+LATEX_HEADER:\pagestyle{fancy}
#+LATEX_HEADER:\fancyhf{}
#+LATEX_HEADER:\usepackage[labelfont=bf]{caption}
#+LATEX_HEADER:\usepackage{setspace}
#+LATEX_HEADER:\setlength{\headheight}{10.2pt}
#+LATEX_HEADER:\setlength{\headsep}{20pt}
#+LATEX_HEADER:\renewcommand{\headrulewidth}{0.5pt}
#+LATEX_HEADER:\renewcommand{\footrulewidth}{0.5pt}
#+LATEX_HEADER:\lfoot{\today}
#+LATEX_HEADER:\cfoot{\copyright\ 2017 W.\ F.\ Schneider}
#+LATEX_HEADER:\rfoot{\thepage}
#+LATEX_HEADER:\chead{\bf{Advanced Chemical Engineering Thermodynamics (CBE 60553)\vspace{12pt}}}
#+LATEX_HEADER:\lhead{\bf{Homework 6}}
#+LATEX_HEADER:\rhead{\bf{Due November 22, 2017}}
#+LATEX_HEADER:\usepackage{titlesec}
#+LATEX_HEADER:\titlespacing*{\section}
#+LATEX_HEADER:{0pt}{0.6\baselineskip}{0.2\baselineskip}
#+LATEX_HEADER:\title{University of Notre Dame\\Advanced Chemical Engineering Thermodynamics\\(CBE 60553)}
#+LATEX_HEADER:\author{Prof. William F.\ Schneider}
#+LATEX_HEADER:\usepackage{siunitx}
#+LATEX_HEADER:\usepackage[version=3]{mhchem}
#+LATEX_HEADER:\def\dbar{{\mathchar'26\mkern-12mu d}}

#+OPTIONS: toc:nil
#+OPTIONS: H:3 num:3
#+OPTIONS: ':t
#+END_OPTIONS

\noindent *Solve each problem on separate sheets of paper, and clearly indicate the problem number and your name on each.  Carefully and neatly document your answers.  You may use a mathematical solver like Matlab or Mathematica. Use plotting software for all plots.*

* It's all a balance
The van der Waals equation of state captures the balance between molecular attractions and repulsions that characterize a real fluid. The Helmholtz free energy of a monatomic van der Waals fluid can be written
   \begin{equation*}
     a_\text{vdW} = \left \{ - RT \ln (v-b) -1.5 R T \ln (R T) \right\} +\left \{ RT -a/v
     \right \}
   \end{equation*}
\noindent where the terms in the first bracket correspond to the entropic repulsive forces and the
terms in the second bracket the energetic attractions.

1. Plot the repulsive, attractive, and total Helmholtz energies of \ce{CO2} at \SI{280}{K}
  vs.\nbsp{}log molar volume from 0.04 to \SI{1}{\liter\per\mole}.  The \ce{CO2} van der Waals constants
  are $a =\SI{3.6551}{\liter\squared\bar\per\mole\squared}$ and $b = \SI{0.042816}{\liter\per\mole}$.

2. <<q:Z>> Plot the compressibility of van der Waals \ce{CO2} vs.\nbsp{}reduced pressure  $P_r$ of $0.1
   < P_r < 10$ at $T_r =1.05$. The critical temperature of \ce{CO2} is $T_c =
   \SI{304.2}{K}$ and critical pressure $P_c = \SI{7.376e6}{\pascal}$.  /Hint/: You will
  have to solve a cubic numerically.  Consider which of the three roots is the relevant
  one.

3. The compressibility of an ideal gas is $Z_\text{ig}=1$.  Explain in terms of
    microscopic interactions why $Z$ is greater or less than 1 for the various values of
    $P_r$ in your Question [[q:Z]] plot.

#+BEGIN_SRC python :exports none
import numpy as np
import matplotlib.pyplot as plt

a = 3.6551
b = 0.042816
R0 = 0.08314472   # bar l / (K mol)

attract = -R0*T*a/v
repel   = -R0*T*(np.log(v-b) - 1.5 * np.log(R0*T)

T = 280.   # K



#+END_SRC

* We had to talk about it at some point
The fugacity $f(T,P)$ of a gas is defined as the function that satisfies

\[
\mu(T,P) =
\mu^\circ(T) + RT \ln \left ( f(T,P)/ P^\circ) \right )
\]
where $\mu^{\circ}(T)$ is the chemical potential of the fluid in an ideal gas reference
state at reference pressure $P^{\circ}$. The fugacity has units of pressure.

1. What is the \(\lim_{P\rightarrow 0} \mu(T,P)\)?  /Hint/: Remember that all gas are ideal in
   the limit of zero pressure or infinite volume.

2. What is the $\lim_{P\rightarrow 0} f(T,P)$?  Why is fugacity a useful concept?

3. Derive a relationship between the residual volume, \(v_{res} = v - v_{ig}\), and
   compressibility \(Z\).

4. Derive the following relationship between fugacity and compressibility.  Use the Gibbs-Duhem relationship between $d\mu$ and the other intensive variables.
   \begin{equation}
     \left ( \frac{\partial\ln\left(f/P\right)}{\partial P} \right )_{T} = \frac{v}{RT} \left ( \frac{Z-1}{Z} \right )
   \end{equation}

5. Because equations of state are usually rational functions in $v$, it is generally
   easier to compute $f(T,v)$ than $f(T,p)$ Use the chain rule to relate the derivative
   above to a derivative in $v$. Evaluate the expression you get assuming the fluid
   follows a one-parameter virial equation of state.

6. Now compute $\ln (f/P)$ for the one-parameter virial equation of state by integrating
   from the ideal gas limit ($v \rightarrow \infty$ to $v$).  Recall that $f\rightarrow P$
   in the ideal gas limit.

7. This ratio $f/P$ is called the fugacity coefficient, $\phi$. When $\phi > 1$, the
   chemical potential is greater than that of an ideal gas at the same density and
   temperature, and vice versa when $\phi < 1$.  Recall we learned that the second virial
   coefficient $B > 0$ at high temperatures, where entropy effects dominate, and $B < 0$
   at low temperatures, where the energetic interactions between molecules dominate.  How
   does the virial EOS chemical potential compare to the ideal gas chemical potential at high
   temperature? At low temperature?  Why?

8. One can do similar calculations for more complex equations of state. Be thankful I
   didn't ask you to. They are a mess. If you need the results, look them up.

#+BEGIN_SRC python :exports none

print('Question 1: negative infinity')
print('Question 2: P')
print('Question 3: because it behaves more nicely in the ideal limit than does mu')

#+END_SRC


# \item \textbf{Real fluids.}  The van der Waals equation is conceptually useful but
#   quantitatively not so great.  Let's compare the performance of some competing equations
#   of state.
#   \begin{enumerate}
#   \item\label{q:Q} Plot the theoretical pressure of \ce{CO2} vs.\ log molar volume from
#     0.04 to 1 L mol$^{-1}$ at 280~K assuming it is
#     \begin{enumerate}
#     \item (1 pt) an ideal gas;
#     \item (3 pts) a van der Waals gas with $a = 3.6551$ L$^2$ bar mol$^{-2}$ and $b =
#       0.042816$ L mol$^{-1}$;
#     \item (3 pts) a Redlich-Kwong gas with $A = 64.597$ L$^2$ bar mol$^{-2}$ K$^{1/2}$ and
#       $B = 0.029677$ L mol$^{-1}$;
#     \item (3 pts) a Peng-Robinson gas with $\alpha=4.192$ bar L$^2$ mol$^{-2}$ and $\beta =
#       0.02665$ L mol$^{-1}$.
#     \end{enumerate}

#   \item\label{q:prob} (2 pts) The density of \ce{CO2}(l) at 280~K is 19.0 mol L$^{-1}$.  What is
#     the density of the corresponding vapor phase according to the Peng-Robinson equation of
#     state?

#   \item (2 pts) Following is some (simulated) data for \ce{CO2} at 250 K.  Infer the second virial
#     coefficient at this temperature.
# \vspace{12pt}

# \begin{tabular}{l | l lllllll}
#  $v$ (L mol$^{-1}$) & 0.3 & 0.4 & 0.5 & 0.6& 0.7 & 0.8 & 0.9 & 1.0 \\
# \hline \\
#  $P$ (bar)    &36.2241 &  32.4641 & 28.7209 & 25.5398 &  22.9091 & 20.7306 & 18.9103 &
#  17.3726 \\
# \end{tabular}

# \item (3 pts) Here's similar data at 350~K.  Determine the second virial coefficient at this
#   temperature and use it to infer the van der Waals constants for \ce{CO2}.

# \vspace{12pt}

# \begin{tabular}{l | l lllllll}
#  $v$ (L mol$^{-1}$) & 0.3 & 0.4 & 0.5 & 0.6& 0.7 & 0.8 & 0.9 & 1.0 \\
# \hline \\
#  $P$ (bar)    &66.6408&54.7339&46.2859&40.0413&35.2569&31.4818&28.4305&25.9146 \\
# \end{tabular}

* Separating an ideal mixture
The exhaust from a coal-fired power plant contains approximately 12\% \ce{CO2} in a
  mixture of other gases, all at \SI{40}{\celsius} and \SI{1}{atm}.

1. What is the minimum work, in kJ/kg \ce{CO2}, to separate the \ce{CO2} from the
  remaining gases at constant $T$ and $P$, assuming the gas mixture is ideal?

2. What is the minimum work of separation if the mixture is non-ideal and obeys the
  Lewis-Randall mixing rules, $\hat{f}_i^{\text{mix}} = y_i f_i$?

\[
W_{min} = -\Delta G_{mix} = (N_A \mu_A(y_A,T) + N_B \mu_B(y_B,T)) - N_A \mu_A(T) - N_B \mu_B(T)
\]

#+BEGIN_SRC python :exports none
import numpy as np

R0 = 8.31441
T = 273.15 + 40
P = 101325       # Pascal

y = 0.12

amix = -R0 * T * (y*np.log(y) + (1-y)*np.log(1-y))

print('Question 1')
print('Ideal work =',amix,'J/mol mixture')
print('Ideal work =',amix*(1./0.12)*(1./0.032)*(1./1000.),'kJ/kg CO2')

print('Question 2')
print('Same answer. Non-ideal parts cancel')
#+END_SRC

#+RESULTS:
: Question 1
: ('Ideal work =', 955.34700234576258, 'J/mol mixture')
: ('Ideal work =', 248.78828186087568, 'kJ/kg CO2')
: Question 2
: Same answer. Non-ideal parts cancel

* And fugacity makes a come-back
The virial equation of state can be generalize for a mixture to

  \begin{equation*}
    \frac{P}{RT} = \frac{N}{V} + \frac{N^2 B_\text{mix}}{V^2} \qquad B_\text{mix} =
    \sum_i\sum_j y_iy_j B_{ij} \qquad B_{ij} = \sqrt{B_iB_j}
  \end{equation*}

1. Derive an expression for the partial molar volume of component $\bar v_{i}$ in the virial
  mixture.  \textit{Hint:} Take advantage of the triple product rule of partial derivatives.

2. The component fugacity \(\hat{f}_{i}(T,P)\) and the corresponding fugacity coefficient $\hat{f}_i/y_i
   P = \phi_i(T,P)$ can be defined in analogy to the expression for the pure component system.
   Use this definition to derive an expression for $\ln \phi_i$ for the virial
   mixture, integrating as appropriate from the ideal gas limit to \(P\).
   \begin{equation}
     \left ( \frac{\partial\ln\left(\hat{f}_{i}/y_{i}P\right)}{\partial P} \right )_{T} = \frac{\bar{v}_{i} - \bar{v}_{ig}}{RT}
   \end{equation}

3. (4 pts) The second virial coefficients of \ce{CO2} and air are \(-110.7\) and
   \(-3 \text{ cm}^3 \text{ mol}^{-1}\) at \(40^\circ\)C. What is the minimum work of
   separation of 12\% \ce{CO2} from \ce{N2} approximating the mixture with the
   virial equation of state?


#+BEGIN_COMMENT
The residual volume in the mixture is a function only of composition and the B's, so can
integrate in pressure.
#+END_COMMENT

